
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: fdxri
spec:
  host: webapp.example.com
  policies:
  - name: jwt-policy
  upstreams:
  - name: fdxri
    service: kubernetes_service.fdxri.metadata.0.name
    port: 8080
  routes:
  - path: /
    action:
      pass: fdxri
 
 ---
 
apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: jwt-policy
spec:
  jwt:
    realm: MyProductAPI
    token: $http_token
    jwksURI: http://keycloak.default.svc.cluster.local:8080/realms/jwks-example/protocol/openid-connect/certs
    keyCache: 1h

