controller:
  appprotect:
    enable: true
  appprotectdos:
    enable: false
  enableSnippets: true
  image:
    repository: private-registry.nginx.com/nginx-ic-nap-dos/nginx-plus-ingress
    tag: 3.1.0
  nginxplus: true
  nginxStatus:
    allowCidrs: 0.0.0.0/0
    port: 9000
  readyStatus:
    initialDelaySeconds: 30
  serviceAccount:
    imagePullSecretName: regcred
  nginxDebug: true
  logLevel: 3
  config:
    entries:
      error-log-level: debug
      log-format:  '$remote_addr - $remote_user [$time_local] "$request" $status  auth header: "$http_authorization" token: "$http_token"'    
prometheus:
  create: true
  
