controller:
  appprotect:
    enable: true
  appprotectdos:
    enable: false
  enableSnippets: true
  image:
    repository: nginx/nginx-ic-nap-dos/nginx-plus-ingress
    tag: 3.1.0
  nginxplus: true
  nginxStatus:
    allowCidrs: 0.0.0.0/0
    port: 9000
  readyStatus:
    initialDelaySeconds: 30
  serviceAccount:
    imagePullSecretName: regcred
  config:
    entries:
      log-format:  '$remote_addr - $remote_user [$time_local] "$request" $status  "$http_authorization"'    
prometheus:
  create: true
  
