controller:
  appprotect:
    enable: true
  appprotectdos:
    enable: true
  enableSnippets: true
  image:
    repository: private-registry.nginx.com/nginx-ic-nap-dos/nginx-plus-ingress
    tag: 3.0.2
  nginxplus: true
  nginxStatus:
    allowCidrs: 0.0.0.0/0
    port: 9000
  readyStatus:
    initialDelaySeconds: 30
  serviceAccount:
    imagePullSecretName: regcred
  logLevel: 1
  nginxDebug: true
  config:
    entries:
      error-log-level: info
      log-format:  '$remote_addr - $remote_user [$time_local] "$request" $status  "$http_authorization"'
prometheus:
  create: true
  
